sanergy/urls.py
from django.contrib import admin
from django.urls import path,include
import sanitation.urls
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from sanitation import views as sanitation_views
from django.conf.urls import url
urlpatterns = [
    path('',include (sanitation.urls)),
    path('admin/', admin.site.urls),
    url('accounts/',include('registration.backends.simple.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sanitation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views







urlpatterns = [
    url(r'^$',views.index, name="homePage"),
    url(r'^payment', views.payment, name='payment'),
    url(r'^toilet', views.toilet, name='toilet'),
    url('access/token', views.getAccessToken, name='get_mpesa_access_token'),
    url('online/lipa', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),
    url(r'^api/payment/$', views.PaymentList.as_view()),
    url(r'^confirmation/$', views.confirmation, name='confrimation'),
    url(r'^bills',views.bills,name='bills'),
    url(r'^search/', views.search_results, name='search_results'),

    #API'S
    url(r'^api/bills/', views.BillsList.as_view()),
    url(r'^all_customer_bills/', views.all_customer_bills, name='all_customer_bills'),

    #profile
    url(r'^my-profile/',views.my_profile, name='my-profile'),
    url(r'^create/profile$',views.create_profile, name='create-profile'),
    url(r'^update/profile$',views.update_profile, name='update-profile'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

sanitation/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    phone_number = models.CharField(default=None,max_length=10)
    id_number =models.CharField(max_length=10,default=None)



class User(models.Model):
    first_name=models.CharField(max_length = 65, blank=True)
    last_name=models.CharField(max_length = 65, blank=True)
    phone_number=models.IntegerField(default=0, blank= True)
    user_id_number= models.IntegerField(default=0, blank=True)
    location=models.CharField(max_length = 65, blank=True)

class Payment(models.Model):
    name = models.CharField(max_length = 65, blank=True)
    account = models.CharField(max_length = 65, blank=True)
    phone_Number= models.CharField(max_length=15)
    amount = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True,blank=True,null=True)

    def __str__(self):
        return self.name

    def save_payment(self):
        self.save()    
    @classmethod
    def search_by_phone_Number(cls,search_term):
        payment = cls.objects.filter(phone_Number__icontains=search_term)
        return payment 

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
# M-pesa Payment models
class MpesaCalls(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    merchant_id = models.TextField(null=False,default="")
    checkout_request_id=models.TextField(null=False,default="")
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call'
        verbose_name_plural = 'Mpesa Calls'

class MpesaCallBacks(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField() 
    merchant_id = models.TextField(null=False,default="")
    checkout_request_id=models.TextField(null=False,default="")
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call Back'
        verbose_name_plural = 'Mpesa Call Backs'

class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    type = models.TextField()
    reference = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()
    organization_balance = models.DecimalField(max_digits=10, decimal_places=2)
    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'
    def __str__(self):
        return self.first_name        

class Toilet(models.Model):
    account_number= models.CharField(max_length=100)
    toilet_tag= models.CharField(max_length=100)
    user_id_number = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def save_toilet(self):
        self.save()

    def __str__(self):

        
        return self.toilet_tag    




class Bills(models.Model):
    amount=models.IntegerField(blank=True)
    phone_number=models.TextField()
    reference=models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True,blank=True,null=True)

    def __str__(self):
        return (self.amount) 

    @classmethod
    def search_by_phone_number(cls,search_term):
        bills = cls.objects.filter(phone_number__icontains=search_term)
        return bills   

    def save_bills(self):

        self.save()

sanitation/forms.py
from django import forms
from.models import *



class PaymentForm(forms.ModelForm):
    class Meta:
        model  = Payment
        fields = ['name','account','phone_Number','amount']

class ToiletForm(forms.ModelForm):
    class Meta:
        model  = Toilet
        fields = ['toilet_tag',]

sanitation/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from .models import *
from .forms import *
from django.shortcuts import get_object_or_404
import requests
from requests.auth import HTTPBasicAuth
import json
from .mpesa_credentials import *
from django.views.decorators.csrf import csrf_exempt
from mpesa_api.core.mpesa import Mpesa
from .serializer import *
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth.decorators import login_required
import datetime as dt
from mpesa_api.core.mpesa import Mpesa
from .serializer import *
from rest_framework.response import Response
from rest_framework.views import APIView

      

#landing page - home page
def index(request):


    return render(request,'index.html',locals())


@login_required(login_url='/accounts/login/')
def my_profile(request):
    current_user=request.user
    profile =Profile.objects.get(username=current_user)
    return render(request,'profile/user_profile.html',{"profile":profile})

# def redirection(request):
#     if user.is_valid() == True:
#         return render(request,'payment.html')    


# @login_required(login_url='/accounts/login/')
# def user_profile(request,username):
#     user = User.objects.get(username=username)
#     profile =Profile.objects.get(username=user)

@login_required(login_url='/accounts/login/')
def create_profile(request):
    current_user=request.user
    if request.method=="POST":
        form =ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()
        return HttpResponseRedirect('/')
    else:
        form = ProfileForm()
        return render(request,'profile/profile_form.html',{"form":form})
    

@login_required(login_url='/accounts/login/')
def update_profile(request):
    current_user=request.user
    if request.method=="POST":
        instance = Profile.objects.get(username=current_user)
        form =ProfileForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()

        return redirect('index')

    elif Profile.objects.get(username=current_user):
         profile = Profile.objects.get(username=current_user)
         form = ProfileForm(instance=profile)
    else:
        form = ProfileForm()

    return render(request,'profile/update_profile.html',{"form":form})
@login_required(login_url='/accounts/login/')
def my_profile(request):
    current_user=request.user
    profile =Profile.objects.get(username=current_user)
    return render(request,'profile/user_profile.html',{"profile":profile})

# def redirection(request):
#     if user.is_valid() == True:
#         return render(request,'payment.html')    


# @login_required(login_url='/accounts/login/')
# def user_profile(request,username):
#     user = User.objects.get(username=username)
#     profile =Profile.objects.get(username=user)

@login_required(login_url='/accounts/login/')
def create_profile(request):
    current_user=request.user
    if request.method=="POST":
        form =ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()
        return HttpResponseRedirect('/')
    else:
        form = ProfileForm()
        return render(request,'profile/profile_form.html',{"form":form})
    

@login_required(login_url='/accounts/login/')
def update_profile(request):
    current_user=request.user
    if request.method=="POST":
        instance = Profile.objects.get(username=current_user)
        form =ProfileForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()

        return redirect('index')

    elif Profile.objects.get(username=current_user):
         profile = Profile.objects.get(username=current_user)
         form = ProfileForm(instance=profile)
    else:
        form = ProfileForm()

    return render(request,'profile/update_profile.html',{"form":form})


def payment(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()

            phone_Number = form.cleaned_data['phone_Number']
            amount = form.cleaned_data['amount']
            lipa_na_mpesa_online(phone_Number, amount)
            return redirect('bills')

    else:
        form = PaymentForm()
    return render(request,'payment.html',locals())

def toilet(request):


    this_user_id_number = User.objects.all()
    if request.method == 'POST':

        form = ToiletForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            phone_Number = form.cleaned_data['phone_Number']
            amount = form.cleaned_data['amount']
            # form.save(commit=False)
            # payment.save()
            lipa_na_mpesa_online(phone_Number, amount)
            return redirect('bills')
    else:
        form = ToiletForm()
    return render(request,'toilet.html',locals())            
   



def getAccessToken(request):
    consumer_key = 'cHnkwYIgBbrxlgBoneczmIJFXVm0oHky'
    consumer_secret = '2nHEyWSD4VjpNh2g'
    api_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'
    r = requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    mpesa_access_token = json.loads(r.text)
    validated_mpesa_access_token = mpesa_access_token['access_token']
    return HttpResponse(validated_mpesa_access_token)

def lipa_na_mpesa_online(phone, amount):

    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = {
        "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
        "Password": LipanaMpesaPpassword.decode_password,
        "Timestamp": LipanaMpesaPpassword.lipa_time,
        "TransactionType": "CustomerPayBillOnline",
        "Amount": amount,
        "PartyA": phone,  # replace with your phone number to get stk push
        "PartyB": LipanaMpesaPpassword.Business_short_code,
        "PhoneNumber": phone,  # replace with your phone number to get stk push
        "CallBackURL": "https://0e070bc3.ngrok.io/confirmation/",
        "AccountReference": "Obindi",
        "TransactionDesc": "Testing stk push"
    }

    response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse('success')    

    response = requests.post(api_url, json=request, headers=headers)   
    if response.status_code==200:
        data = response.json()
        if 'ResponseCode' in data.keys():
            if data['ResponseCode']==0:
                merchant_id = data['MerchantRequestID']
        pass
    merchant_id = response
    print(response.json())



@csrf_exempt
def register_urls(request):
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
    headers = {"Authorization": "Bearer %s" % access_token}
    options = {"ShortCode": LipanaMpesaPpassword.Business_short_code,
               "ResponseType": "Completed",
               "ConfirmationURL": "http://127.0.0.1:8000/api/v1/c2b/confirmation",
               "ValidationURL": "http://127.0.0.1:8000/api/v1/c2b/validation"}
    response = requests.post(api_url, json=options, headers=headers)
    return HttpResponse(response.text)
@csrf_exempt
def call_back(request):
    pass
@csrf_exempt
def validation(request):
    context = {
        "ResultCode": 0,
        "ResultDesc": "Accepted"
    }
    return JsonResponse(dict(context))
@csrf_exempt
def confirmation(request):
    mpesa_body =request.body.decode('utf-8')
    try:
        mpesa_payment = json.loads(mpesa_body)
    except Exception as e:
        print(e)
        context = {
            "ResultCode": 1,
            "ResultDesc": "Accepted"
        }
        return JsonResponse(dict(context)) 
    print(mpesa_payment) 
    if mpesa_payment['Body']['stkCallback']['ResultCode']==0:
        mpesa_payment = mpesa_payment['Body']['stkCallback']['CallbackMetadata']['Item']
        print(mpesa_payment)
        # payment = MpesaPayment(
        #     first_name=mpesa_payment['FirstName'],
        #     last_name=mpesa_payment['LastName'],
        #     middle_name=mpesa_payment['MiddleName'],
        #     description=mpesa_payment['TransID'],
        #     phone_number=mpesa_payment[4]['Value'],
        #     amount=mpesa_payment[0]['Value'],
        #     reference=mpesa_payment[1]['Value'],
        #     organization_balance=mpesa_payment['OrgAccountBalance'],
        #     type=mpesa_payment['TransactionType'],
        # )
        # payment.save()
        b = Bills(
           phone_number=mpesa_payment[4]['Value'],
           reference=mpesa_payment[1]['Value'],
           amount=mpesa_payment[0]['Value']
        ) 
        b.save()
        context = {
            "ResultCode": 0,
            "ResultDesc": "Accepted"
        }
        return JsonResponse(dict(context))    



class PaymentList(APIView):
    def get(self, request, format=None):
        all_mpesapayment = MpesaPayment.objects.all()
        serializers = MpesaPaymentSerializer(all_mpesapayment   , many=True)
        return Response(serializers.data)

        

   

#consuming mpesa api biils

def bills(request):
    url = 'https://sandbox.safaricom.co.ke/mpesa/?api_key=ZGWH5CJonGUS9C7eRzvkQGgzMJShHaDD'
    response = requests.get(url.format()).json()
    details = []
    for detail in details:
        amount = detail.get('amount')

sanitation/templates/all_bills.html
{%extends "registration/base.html"%}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
​
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <title>Bills</title>
</head>
​
<body >

  {% block content %}
   <style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #eedc12;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: black;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: black;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Style the "active" element to highlight the current page */
.topnav a.active {
  background-color: #2196F3;
  color: white;
}

/* Style the search box inside the navigation bar */
.topnav input[type=text] {
  float: right;
  padding: 6px;
  border: none;
  margin-top: 8px;
  margin-right: 16px;
  font-size: 17px;
}

/* When the screen is less than 600px wide, stack the links and the search field vertically instead of horizontally */
@media screen and (max-width: 600px) {
  .topnav a, .topnav input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }
  .topnav input[type=text] {
    border: 1px solid #ccc;
  }
}
</style>
</head>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a class="logo" href="{% url 'homePage' %}">
  <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
  <br>
  <br>
  <a href="{% url 'homePage' %}" style="text-align:center">Logout</a>
  <br>
  <br>
  <a href="#" style="text-align:center">Clients</a>
  
</div>

<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
  <br>
​<div class="topnav">
  <div class="col-sm-4 col-md-4 navbar-right">

            <form class="navbar-form" method="GET" role="search" action="{%url 'search_results'%}" >
    
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search Bills" name="payment">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
              </div>
    
            </form>
          </div>
</div>
  
  <h2 style="text-align:center;color:#005486ff;font-weight:bold;font-size:38px;">BILL DETAILS</h2>
  <br>
  <div class="container"></div>
  <div class="row">
  
  <div class="col-md-1"></div>
  
<div class="col-md-10">
  <table class="table table-bordered table-primary" id="tblCustomers" cellspacing="0" cellpadding="0">
    <tr>
      <th>No</th> 
      <th>Bill Amount</th> 
      <th>Bill Phone Number</th> 
      <th>Bill reference</th>
      <th>Date</th>
    </tr>
    {% for customer_bill in customer_bills%}
​
    <tr>
      <td>{{customer_bill.id}}</td>
      <td>{{customer_bill.amount}}</td>
      <td>{{customer_bill.phone_number}}</td>
      <td>{{customer_bill.reference}}</td>
      <td>{{customer_bill.timestamp}}</td>

    </tr>
    {% endfor %}
​
</table>
<br/>
<br>
<br>
<input class="btn btn-primary" type="button" id="btnExport" value="Export" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script type="text/javascript">
    $("body").on("click", "#btnExport", function () {
        html2canvas($('#tblCustomers')[0], {
            onrendered: function (canvas) {
                var data = canvas.toDataURL();
                var docDefinition = {
                    content: [{
                        image: data,
                        width: 500
                    }]
                };
                pdfMake.createPdf(docDefinition).download("Table.pdf");
            }
        });
    });
</script>
<div class="col-md-1"></div>
</div>
</div>
  {% endblock %}
​
  
  </body>
</html>

sanitation/templates/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sanergy</title>

    {%block styles%}
      {%bootstrap_css%}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {%endblock%}

  </head>
  <body> 
    {% block content %}
      {% include "navbar.html" %}
    {% endblock %}

    {% block scripts %}
      {% bootstrap_javascript %}
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>
    {% endblock %}
  </body>
</html>

sanitation/templates/bills.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3 %}
{% load static %}


<body style="background:url('static/img/slum.jpg');text-align:center;">

<br>
<br>

<style>
    table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  border-spacing: 5px;

}

th, td {
  padding: 15px;
}
th {
  text-align: left;
}
</style>

    <div class="container">
    <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
    <br>
    <br>
    <br>
        <h1 style="font-weight:bold;font-size:65px; color:#eedc12;">Payments</h1>
        <br>
        <br>
        <br>
        
        <br>
        
        <table style="width:100%; color:#eedc12">     
  
  <tr style="font-weight:bold;font-size:25px;">
    <th style="font-weight:bold;font-size:30px;">Telephone</th>
    <td>0707096346</td>
    <td>0745577855</td>
    <td>0763466346</td>
    <td>0745749355</td>
  </tr>
  <tr style="font-weight:bold;font-size:25px;">
    <th style="font-weight:bold;font-size:30px;"> Account:</th>
    <td>2584994783</td>
    <td>6395783904</td>
    <td>4795799478</td>
    <td>7047836859</td>
  </tr>
  <tr style="font-weight:bold;font-size:25px;">
    <th style="font-weight:bold;font-size:30px;">Date:</th>
    <td>8.09.2019</td>
    <td>7.09.2019</td>
    <td>6.09.2019</td>
    <td>6.09.2019</td>
  </tr>
  
  
</table>


       
    </div>

        {% endblock %}
</body>

sanitation/templates/data.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}

<div class="container">
    <div id="logo">
    
    <a class="logo" href="http://www.sanergy.com">
    <img class="fixed-logo" src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="160px" alt="Sanergy">
    <img class="nav-logo" src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-white-195.png" width="160px" alt="Sanergy">
    </a>
   
      
</div>     
    

      {% endblock %}

      {% endblock %}

sanitation/templates/payment.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}

<style>

#id_name{
    height: 50px;
    border-radius: 105px;
    font-size:17px;
    color: #eedc12;
    font-weight:bold;
}
#id_account{
    height: 50px;
    border-radius: 105px;
    font-size:17px;
    color: #eedc12;
    font-weight:bold;
}

#id_phone_Number{
    height: 50px;
    border-radius: 105px;
    font-size:17px;
    color: #eedc12;
    font-weight:bold;
}
#id_amount{
    height: 50px;
    border-radius: 105px;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
input[type=text] {
  background-color: black;
  color: white;
}

</style>
<body style="background: white;">
<br>
<br>



    <div class="container" style="background-color:none;text-align:center; color:#005486ff; font-size:25px;padding-left:200px;padding-right:200px;">
      
        <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
        <br>
        <br>
        <br>
        <form action="{% url 'payment' %}" method="POST" enctype="multipart/form-data" style="background:none; ">




        <form action="{% url 'payment' %}" method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Pay" style="border-radius: 15px 50px 30px; color:#eedc12 ;font-size:25px">
        </form>

</body>






{% endblock %}

sanitation/templates/search.html
{%extends 'base.html'%} 
{% block content %}
<body  style="background:url('static/img/slum.jpg');text-align:center;">
  
​
        <div class="container">
​
            <div class="row"  style="background:url('static/img/slum.jpg');text-align:center;">
              {% if payment %}
             <h2>Found {{ payment|length }} of searched term {{message}}</h2>
            {% else %}
              <h2> Found 0 payment for the search term {{message}}</h2>
            {% endif %}
​
             </div>
​
            <div class="row">
​
            {% if payment %}
            {% for payment in payment %}
            <div class="col-sm-6 col-md-3">
            <h1>{{payment.name}}</h1>
          <p>{{ payment.amount}}</p>
          <p>{{payment.account}}</p>
          <p>{{payment.phone_Number}}</p>
          <p>{{payment.timestamp}}</p>
​
​
            </div>
             {% endfor %}
                {% endif %}
             </div>
            </div>
</body> 
{% endblock %}

sanitation/templates/toilet.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}

<style>

#id_account_number{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
#id_toilet_tag{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
input[type=text] {
  background-color: black;
  color: white;
}
</style>
<body style=" background: white;" >
<br>
<br>


    <div class="container"style="background-color:none;text-align:center; color:#005486ff; font-size:20px">
    <br>
        
        <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
        <br>
        <br>
        <br>
        <br>
       
        
        <br>
  
            
            <form action="{% url 'toilet' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <br>
                
                <input type="submit" class="btn btn-primary" value="Register" style="border-radius: 25px 50px 30px; color:#eedc12 ;font-size:20px">
            </form>
        
    </div>
</body>
{% endblock %}